[package]
name = "scarb-eject"
version = "1.0.0"
edition = "2021"
rust-version = "1.68"

authors = ["Software Mansion <contact@swmansion.com>"]
description = "Create cairo_project.toml for a given Scarb package."
license = "MIT"
readme = "README.md"
repository = "https://github.com/software-mansion-labs/scarb-eject"

[dependencies]
anyhow = "1.0.71"
cairo-lang-project = "1.1.0"
clap = { version = "4.3.0", features = ["derive"] }
scarb-metadata = "1.4.2"
toml = "0.7.4"

[profile.release]
lto = true
